## MIT 18.065 - Matrix Methods in Data Analysis, Signal Processing, and Machine Learning

## Problems for Lecture 1 (from textbook Section I.1)

In [1]:
include("local_startup.jl");

In [2]:
include("KTBC.jl");

**LaTeX Setup** (run this cell early)
$$
\newcommand{\cv}[1]{\begin{bmatrix} #1 \end{bmatrix}}
\newcommand{\mat}[1]{\begin{bmatrix} #1 \end{bmatrix}}
\newcommand{\norm}[1]{\left\| #1 \right\|}
\newcommand{\abs}[1]{\left| #1 \right|}
$$

Verify: $x = \cv{1 \\ 2}$

#### Problems

#### 1. Give an example where a combination of three nonzero vectors in R⁴ is the zero vector. Then write your example in the form Ax = 0. What are the shapes of A and x and 0?

In [3]:
a,b,c = [1,1,0,0], [-1,-1,1,1] ,[0,0,-1,-1]

([1, 1, 0, 0], [-1, -1, 1, 1], [0, 0, -1, -1])

In [4]:
a + b + c

4-element Vector{Int64}:
 0
 0
 0
 0

In [5]:
A=[a b c]

4×3 Matrix{Int64}:
 1  -1   0
 1  -1   0
 0   1  -1
 0   1  -1

In [6]:
x=[1,1,1]

3-element Vector{Int64}:
 1
 1
 1

In [7]:
z=A*x

4-element Vector{Int64}:
 0
 0
 0
 0

In [8]:
Lx("$A*$x=$z")

L"$\left[
\begin{array}{ccc}
1 & -1 & 0 \\
1 & -1 & 0 \\
0 & 1 & -1 \\
0 & 1 & -1 \\
\end{array}
\right] \cdot \left[
\begin{array}{c}
1 \\
1 \\
1 \\
\end{array}
\right] = \left[
\begin{array}{c}
0 \\
0 \\
0 \\
0 \\
\end{array}
\right]$"

#### 4. Suppose A is the 3 by 3 matrix ones(3, 3) of all ones. Find two independent vectors x and y that solve Ax = 0 and Ay = 0. Write that first equation Ax = 0 (with numbers) as a combination of the columns of A. Why don't I ask for a third independent vector with Az = 0?

In [9]:
A=ones(3,3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [10]:
x1=[2,-1,-1]

3-element Vector{Int64}:
  2
 -1
 -1

In [11]:
A*x1

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [12]:
x2=[-1,2,-1]

3-element Vector{Int64}:
 -1
  2
 -1

In [13]:
A*x2

3-element Vector{Float64}:
 0.0
 0.0
 0.0

These are all of unique vectors that result in A*x = 0, but a1 == -a2 -a3, therefore, there are only two independent vectors. 

These solutions are in the NullSpace of A. Moreover, since there are two indendent vectors, the Rank of A is 2.

In [15]:
Z=stack([[2, -1, -1],
[-1, 2, -1],
[-1, -1, 2]])

3×3 Matrix{Int64}:
  2  -1  -1
 -1   2  -1
 -1  -1   2

In [16]:
rank(Z)

2

In [17]:
Z[1,:] == - Z[2,:] - Z[3,:] # Cols

true

In [18]:
Z[:,1] == - Z[:,2] - Z[:,3] # Rows

true

#### 9. Suppose the column space of an m by n matrix is all of R³. What can you say about m? What can you say about n? What can you say about the rank r?

Since it spans R^3, m>=3 and n>=3.

If the column space of mxn spans R^3 then in must have 3 independent column vectors.

The rank is 3

#### 18. If A = CR, what are the CR factors of the matrix [0 A; 0 A]?

In [19]:
Lx("[0 A; 0 A]")

L"$\left[
\begin{array}{cc}
0 & A \\
0 & A \\
\end{array}
\right]$"

A concrete example

In [20]:
k=10
A = [0 k; 0 k]

2×2 Matrix{Int64}:
 0  10
 0  10

In [21]:
C = [k k; k k]

2×2 Matrix{Int64}:
 10  10
 10  10

In [22]:
R=[0 1/2; 0 1/2]

2×2 Matrix{Float64}:
 0.0  0.5
 0.0  0.5

In [23]:
C*R

2×2 Matrix{Float64}:
 0.0  10.0
 0.0  10.0

In [24]:
A==C*R

true

In [25]:
Lx("$A = $C*$R")

L"$\left[
\begin{array}{cc}
0 & 10 \\
0 & 10 \\
\end{array}
\right] = \left[
\begin{array}{cc}
10 & 10 \\
10 & 10 \\
\end{array}
\right] \cdot \left[
\begin{array}{cc}
0.0 & 0.5 \\
0.0 & 0.5 \\
\end{array}
\right]$"

More generally

In [26]:
Lx("[0 K; 0 K] = [K K; K K]*[0 1/2; 0 1/2]")

L"$\left[
\begin{array}{cc}
0 & K \\
0 & K \\
\end{array}
\right] = \left[
\begin{array}{cc}
K & K \\
K & K \\
\end{array}
\right] \cdot \left[
\begin{array}{cc}
0 & \frac{1}{2} \\
0 & \frac{1}{2} \\
\end{array}
\right]$"